### ISSUE TITLE
Remove Task module

### ISSUE THREAD

**Issue by flinden68** [nl-portal/nl-portal-backend-libraries#103]
As far I can all the Task (Taak) functionality is moved to the ZGW -> Taak module.
It is not used as dependency anymore in the nl-portal-backend-template project

@petervanmanenritense what do you think to proceed with this??

**Comment by petervanmanenritense** [comment]
@flinden68 lets merge and test it!

**Comment by flinden68** [comment]
@petervanmanenritense ok, so lets make the changes to see if it fails ;-)

**Comment by flinden68** [comment]
Fixed in #188
