### ISSUE TITLE
Geuploade bestanden scannen op virussen

### ISSUE THREAD

**Issue by ThomasMinkeRitense** [nl-portal/nl-portal-backend-libraries#15]
## Doel

Het virus-scannen van alle bestanden die in het Portaal worden geupload.

## Context / achtergrond

In het Portaal kunnen gebruikers bestanden uploaden, bijvoorbeeld bij het invullen van een taakformulier. 
Die bestanden moeten op virussen worden gecontroleerd om te voorkomen dat schadelijke bestanden worden opgeslagen op de schijf van het DMS. 

## Wat moet er gebeuren - wat is er nog niet en hebben we wel nodig?

Optionele integratie tussen de Portal backend en een ClamAV service die als Docker container draait. Terugkoppeling van het scanresultaat naar de Portal frontend.

## Wat is het eindresultaat?

Alle bestanden worden gescand voordat ze worden opgeslagen in de Documenten API. Gebruikers krijgen feedback als een bestand niet geaccepteerd wordt.

## Wat valt er buiten scope?

- Het configureren van een ClamAV instantie/service in de infrastructuur. Deze bestaat als het goed is al.

## Acceptatie criteria
- Alle bestanden worden gescand voordat ze worden opgeslagen in de Documenten API
- De ClamAV implementatie wordt via een interface geïmplementeerd zodat er later andere implementaties kunnen worden toegevoegd.
- Standaard wordt geen virusscanning uitgevoerd. Om deze feature aan te zetten moet dit geconfigureerd worden in de applicatie instellingen (application.yaml of ENV).
- De licentie van de gebruikte ClamAV library is compatible met EUPL
- De implementatie gebruikt de clamd service van de host

## Dev note
- De DataBuffer / InputStream kan je maar 1 keer uitlezen, dus de inhoud moet worden gekopieerd BufferedInputstream of vergelijkbaar.
- Unit tests: waar mogelijk
- Integration tests: happy flow (geen virus), via Docker

## Impact - hoeveel inspanning kost dit? 
Inschatting door PO: M  
Inschatting door SA: M (3-4 dagen)

**Comment by flinden68** [comment]
https://github.com/nl-portal/nl-portal-backend-libraries/pull/46
