### ISSUE TITLE
Add payment module

### ISSUE THREAD

**Issue by flinden68** [nl-portal/nl-portal-backend-libraries#203]
There is a need for a payment module to support the payment process in the NL Portal
Specifications see, https://raakvlak.notion.site/0-5-Online-betaling-via-portaal-cde223c3d9194b56a130130090f24a30

- Ogone will be the preferred payment provider
- BE should have an endpoint to collect the payment properties and calculate a hash for safe data transfer to Ogone
- FE should do the actual submission of a html form with payment fields to do the payment
- We need a failure and success callback url to return to after payment
- Support for multiple pspIds

**Comment by petervanmanenritense** [comment]
A few additional things we need to think of/implement:
1. The backend must generate a payment based on an object
2. The result of the payment should always be stored in that object
3. Storing the result of the payment should always work, also when the authentication session has ended, when a user does the payment on a phone and the redirect after the payment is opened in a different browser (this happens on iOs to people that use chrome). I believe this is called server to server in ogone.

**Comment by flinden68** [comment]
1. the transaction stored in a DB is the current procedure in Mijn Den Haag Portal. Currently we have a Task as starting point for a payment. After successful payment you will return to the task and the FE will complete the task
2. functionality could be added if needed
3. functionality could be added if needed, BTW for a payment there is no need for authentication
