### ISSUE TITLE
New version TaakObject

### ISSUE THREAD

**Issue by flinden68** [nl-portal/nl-portal-backend-libraries#221]
With the implementation of the payment module, there is a need of upgrade of the TaakObject to support also payments

`{
  "type": "object",
  "title": "ObjectType Taak",
  "examples": [
    {
      "titel": "Check loan",
      "status": "open",
      "soort": "formtaak",
      "verloopdatum": "2023-09-20T18:25:43.524Z",
      "identificatie": {
        "type": "bsn",
        "value": "82395551"
      },
      "koppeling": {
        "registratie": "zaak",
        "identificatie": "https://openzaak.gemeente.nl/zaken/api/v1/zaken/5551a7c5-4e92-43e6-8d23-80359b7e22b7"
      },
      "url": {
        "uri": "https://google.com"
      },
      "formtaak": {
        "formulier": "http://localhost:8010/api/v2/objects/4e40fb4c-a29a-4e48-944b-c34a1ff6c8f4",
        "data": {
          "voornaam": "Jan",
          "achternaam": "Smit",
          "toestemming": true,
          "geboortedatum": "01-01-1970"
        },
        "verzonden_data": {
          "voornaam": "Jan",
          "achternaam": "Smit",
          "toestemming": false,
          "geboortedatum": "01-01-1971"
        }
      },
      "ingenicobetaling": {
        "bedrag": 147.43,
        "betaalkenmerk": "abcdef1234",
        "pspid": "MyID"
      },
      "verwerker_taak_id": "18af0b6a-967b-4f81-bb8e-a44988e0c2f0"
    }
  ],
  "required": [
    "titel",
    "status",
    "soort",
    "identificatie",
    "verwerker_taak_id"
  ],
  "properties": {
    "titel": {
      "type": "string"
    },
    "status": {
      "enum": [
        "open",
        "ingediend",
        "verwerkt",
        "gesloten"
      ],
      "type": "string"
    },
    "verloopdatum": {
      "type": "string",
      "format": "date-time"
    },
    "identificatie": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "verwerker_taak_id": {
      "type": "string",
      "format": "uuid"
    },
    "koppeling": {
      "type": "object",
      "properties": {
        "registratie": {
          "enum": [
            "zaak",
            "product"
          ],
          "type": "string"
        },
        "identificatie": {
          "type": "string",
          "format": "uri"
        }
      },
      "additionalProperties": false
    },
    "soort": {
      "$ref": "#/$defs/soort"
    },
    "url": {
      "$ref": "#/$defs/url"
    },
    "formtaak": {
      "$ref": "#/$defs/formtaak"
    },
    "ingenicobetaling": {
      "$ref": "#/$defs/ingenicobetaling"
    }
  },
  "$defs": {
    "soort": {
      "enum": [
        "url",
        "formtaak",
        "ogonebetaling"
      ],
      "type": "string"
    },
    "url": {
      "type": "object",
      "properties": {
        "uri": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "uri"
      ],
      "additionalProperties": false
    },
    "formtaak": {
      "type": "object",
      "properties": {
        "formulier": {
          "type": "string",
          "format": "uri"
        },
        "data": {
          "type": "object",
          "additionalProperties": true
        },
        "verzonden_data": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "required": [
        "formulier"
      ],
      "additionalProperties": false
    },
    "ingenicobetaling": {
      "type": "object",
      "properties": {
        "bedrag": {
          "type": "number",
          "minimum": 0,
          "multipleOf": 0.01
        },
        "betaalkenmerk": {
          "type": "string"
        },
        "pspid": {
          "type": "string"
        }
      },
      "required": [
        "bedrag",
        "betaalkenmerk",
        "pspid"
      ],
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}`

**Change**
- mark old fields as Deprecated but keep them for backwards compatibility
- add the new fields
- additionalProperties = true in JSON schema, so new and old properties are accepted

**Comment by nielserkamp-ritense** [comment]
@flinden68 Currently, there is a discussion happening about the taak object w.r.t. payments and future proofing it. Is this change applied anywhere so far?

**Comment by flinden68** [comment]
I think Ritense is already in the loop on the changes

**Comment by flinden68** [comment]
PR see #240
