### ISSUE TITLE
Gebruikersvriendelijkere pagina als er geen lopende zaken zijn

### ISSUE THREAD

**Issue by ThomasMinkeRitense** [nl-portal/nl-portal-backend-libraries#23]
Als NL Portal gebruiker
Wil ik dat de 'lopende zaken' pagina een vriendelijkere melding geeft
Zodat ik niet alleen de botte tekst 'Er zijn geen lopende zaken.' zie

**Comment by flinden68** [comment]
verplaatst naar frontend libraries
