### ISSUE TITLE
Ondersteuning meerdere Documenten-API configuraties

### ISSUE THREAD

**Issue by theo-ritense** [nl-portal/nl-portal-backend-libraries#24]
Op dit moment wordt er enkel 1 configuratie ondersteund voor de Documenten-API.
De wens is om meerdere configuraties te ondersteunen, en dat de juiste configuratie wordt geselecteerd obv de document-URL.

Het plugin framework wat al beschikbaar is in Valtimo, is mogelijk bruikbaar binnen de portal. Dit framework ondersteund al meerdere configuraties per plugin.

Via een spike willen we erachter komen:
 - of de gewenste oplossing werkbaar is
 - of er aanpassingen nodig zijn in het framework
 - hoeveel tijd dit gaat kosten 
 - hoe de authenticatie in zijn werk gaat binnen de portal

**Comment by Geert-Jan-DH** [comment]
Ik denk dat de classificatie "wens" onjuist is. De inrichting met meerdere DMSen wordt ondersteund vanuit OpenZaak, en de juiste URL's zijn via de te gebruiken en aanwezige API's ook opvraagbaar.

Het gebruik van een tweede DMS is in overleg met architect Jan Verbeek ingevoerd omdat dit volgens de richtlijnen en de mogelijkheden toegestaan is. 

Voor mij als functioneel beheerder hiervan is dit nu dan ook een belemmerde "bug", ondanks het feit dat dit mogelijk nooit voorzien is bij de ontwikkeling van het Klantportaal. 
Onze gebruikers krijgen bij het gebruik van het Klantportaal dat "out of the box" zou werken nu een foutmelding zodra er een document gekoppeld is aan een zaak. De rest van de zaak wordt ook niet getoond.

**Comment by petervanmanenritense** [comment]
@JanBrek op dit moment kent de portal alleen de document uuid's, de vertaling van uuid naar document url wordt gedaan in de backend. Is het voor Den Haag acceptabel als we de volledige document url's meesturen (documentapi.test.denhaag.nl/enkelvoudigeinformatieobject/uuid=123-sdfgdsfg2345-assdf23-213) naar de klantportaal?

**Comment by JanBrek** [comment]
Hier ook nog even; Zoals besproken lijkt dat de only-way-to-go voor nu
