### ISSUE TITLE
Support type/value structure of form field in task object

### ISSUE THREAD

**Issue by ThomasMinkeRitense** [nl-portal/nl-portal-backend-libraries#40]
GraphQL now:
`query {
	GetTasks {
		  getTasks {
			    content {
					id  
					objectId      
					formId  
					title      
					status      
					date      
					data      
			}
		}
	}`

Should be:
`query {
    getTaken { 
        content { 
            date  
            formulier {
                type //id of url
                value //https://objectenapi.nl/uuid
            }
            id
            objectId
            status
            identificatie {
                type
                value
            }
        } 
    }
}`

Include type in request to get form definition. Based on type, BFF should either serve form definition from database (type = id) or retrieve form definition from the Objecten API (type = url)

**Comment by flinden68** [comment]
fixed in PR in nl-portal-frontend-libraries, https://github.com/nl-portal/nl-portal-frontend-libraries/pull/41
