### ISSUE TITLE
Move backend to Spring 3

### ISSUE THREAD

**Issue by JanBrek** [nl-portal/nl-portal-backend-libraries#45]
Spring 2 will be end of support on 18 october for open source(?)

Both Backend-libraries & -libraries need to be updated to Spring 3.

- Spring security must be carefully checked as it has some breaking changes
- GraphQl also has some compatibility issues

**Comment by flinden68** [comment]
May be also align all the package dependencies and use as much TestDependencies and Depedencies from the buildSrc. It will increase the maintainability with the dependencies and versions in place

**Comment by flinden68** [comment]
fixed with #50 and #120
